# apphosting.yaml
apphosting:
  run:
    # Specifies the Node.js runtime environment for the application.
    runtime: nodejs20

  env:
    # 🔑 Firebase Public Config (Available to both Next.js build and runtime/client)

    NEXT_PUBLIC_FIREBASE_API_KEY:
      secret: projects/veas-acoustics-100/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
      availability:
        - BUILD
        - RUNTIME

    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:
      secret: projects/veas-acoustics-100/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
      availability:
        - BUILD
        - RUNTIME

    NEXT_PUBLIC_FIREBASE_PROJECT_ID:
      secret: projects/veas-acoustics-100/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
      availability:
        - BUILD
        - RUNTIME

    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:
      secret: projects/veas-acoustics-100/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
      availability:
        - BUILD
        - RUNTIME

    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:
      secret: projects/veas-acoustics-100/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest
      availability:
        - BUILD
        - RUNTIME

    NEXT_PUBLIC_FIREBASE_APP_ID:
      secret: projects/veas-acoustics-100/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest
      availability:
        - BUILD
        - RUNTIME

    NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID:
      secret: projects/veas-acoustics-100/secrets/NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID/versions/latest
      availability:
        - BUILD
        - RUNTIME

    # 🔗 Optional Extras (Simple non-secret values)

    NEXT_PUBLIC_CONTACT_FUNCTION_URL: "https://handlecontactform-pa7cj3ngwa-nw.a.run.app"
    NEXT_PUBLIC_ALLOW_FIRESTORE_EXPORT: "true"

    # 🔒 Sensitive Key (Runtime only - not exposed to client-side code)
    
    RESEND_API_KEY:
      secret: projects/veas-acoustics-100/secrets/RESEND_API_KEY/versions/latest
      availability:
        - RUNTIME