# apphosting.yaml - FINAL CLEANUP SCRIPT
apphosting:
  run:
    # Specifies the Node.js runtime environment.
    runtime: nodejs20

  env:
    # 🔗 Optional Extras (Simple non-secret values)
    # These remain as key/value pairs and should still be safe.
    NEXT_PUBLIC_CONTACT_FUNCTION_URL: "https://handlecontactform-pa7cj3ngwa-nw.a.run.app"
    NEXT_PUBLIC_ALLOW_FIRESTORE_EXPORT: "true"

    # 🔒 Sensitive Key (FETCHED FROM SECRET MANAGER)
    # This must remain a secret, as it is needed on the server (runtime).
    RESEND_API_KEY:
      secret: projects/veas-acoustics-100/secrets/RESEND_API_KEY/versions/latest
      availability:
        - RUNTIME

# NOTE: All NEXT_PUBLIC_FIREBASE_... keys have been removed from this file 
# and moved into your application code (src/config/firebase.ts) to bypass the 
# App Hosting environment injection failure.