# .apphosting.yaml
apphosting:
  run:
    # The runtime (matches your Node engine)
    runtime: nodejs20

    # Environment variables (map Secret Manager secrets)
    env:
      # Firebase public config
      NEXT_PUBLIC_FIREBASE_API_KEY: projects/veas-acoustics-100/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: projects/veas-acoustics-100/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: projects/veas-acoustics-100/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: projects/veas-acoustics-100/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: projects/veas-acoustics-100/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest
      NEXT_PUBLIC_FIREBASE_APP_ID: projects/veas-acoustics-100/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: projects/veas-acoustics-100/secrets/NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID/versions/latest

      # Optional extras
      NEXT_PUBLIC_CONTACT_FUNCTION_URL: "https://handlecontactform-pa7cj3ngwa-nw.a.run.app"
      NEXT_PUBLIC_ALLOW_FIRESTORE_EXPORT: "true"

      # Any other shared secrets
      RESEND_API_KEY: projects/veas-acoustics-100/secrets/RESEND_API_KEY/versions/latest
