name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          create_credentials_file: true

      - name: Set GCP project
        run: gcloud config set project ${{ secrets.GCP_PROJECT }}

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js (static export)
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      - name: Deploy to Firebase Hosting (use .firebaserc default)
        run: |
          firebase deploy \
            --non-interactive \
            --only hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks
