name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to GCP using Workload Identity Federation
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set GCP project
        run: gcloud config set project ${{ secrets.GCP_PROJECT }}

      - name: Test GCP authentication
        run: gcloud projects describe ${{ secrets.GCP_PROJECT }}

      # Optional: Deploy Firebase Hosting
      # - name: Deploy Firebase Hosting
      #   run: |
      #     npm ci
      #     npx firebase deploy --only hosting
