name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # Required for Workload Identity Federation
      contents: read

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Authenticate to GCP using Workload Identity Federation
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/734640373537/locations/global/workloadIdentityPools/github-actions-pool-3/providers/github-oidc
          service_account: github-action@veas-website-01.iam.gserviceaccount.com
          token_format: access_token
          access_token_lifetime: 3600s

      # 3️⃣ Set GCP project
      - name: Set GCP project
        run: gcloud config set project veas-website-01

      # 4️⃣ Install Node dependencies and build Next.js
      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      # 5️⃣ Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      # 6️⃣ Deploy to Firebase Hosting + Functions
      - name: Deploy to Firebase
        run: |
          firebase deploy \
            --project veas-website-01 \
            --non-interactive \
            --only hosting,functions \
            --token "${{ steps.auth.outputs.access_token }}"
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
